version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: proy-events-frontend
    networks:
      - web-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    ports:
      - "5001:5001"
    container_name: proy-events-backend
    environment:
      - NODE_ENV=production
    networks:
      - web-network

networks:
  web-network:
    external: true
